const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),source=path.join(root,'research/original-viewer'),web=path.join(root,'dist/web');
if(!fs.existsSync(path.join(source,'main.js')))throw Error('缺少本地原版渲染资源。请先运行 node scripts/import-renderer.cjs <已提取资源目录的绝对路径>；详见 docs/开发说明.md。');
fs.mkdirSync(web,{recursive:true});
const original=fs.readFileSync(path.join(source,'main.js'));
const fingerprint=crypto.createHash('sha256').update(original).digest('hex');
if(fingerprint!=='47f36abaabd34f7d54a95df40d942b609c02db9f5c04d56b124a048571b9f16d')throw Error(`不支持的 Antigravity 资源版本: ${fingerprint}`);
for(const name of ['main.js','prism_bundle.js','jetbox.css','compiled_tailwind.css','theme.css'])fs.copyFileSync(path.join(source,name),path.join(web,name));
fs.copyFileSync(path.join(source,'katex.min.css'),path.join(web,'katex.min.css'));
fs.cpSync(path.join(source,'fonts'),path.join(web,'fonts'),{recursive:true});
fs.cpSync(path.join(source,'workers'),path.join(web,'workers'),{recursive:true});
const baseline=fs.readFileSync(path.join(source,'index.html'),'utf8');
if(!baseline.includes('<header'))throw Error('原版资源的 index.html 缺少本地页面外壳 <header 分界');
let header=baseline.slice(0,baseline.indexOf('<header'));
header=header.replace('</head>','<link rel="stylesheet" href="app.css"><link rel="stylesheet" href="katex.min.css"></head>').replace('<title>Antigravity 原版渲染验证</title>','<title>Artifacts</title>');
const shell=`<div id="artifacts-app"></div><script src="prism_bundle.js"></script><script src="main.js"></script><script src="app.js"></script></body></html>`;
fs.writeFileSync(path.join(web,'index.html'),header+shell);
fs.copyFileSync(path.join(root,'src/viewer/app.js'),path.join(web,'app.js'));
fs.copyFileSync(path.join(root,'src/viewer/app.css'),path.join(web,'app.css'));
console.log(`Built original renderer ${fingerprint.slice(0,12)} with shared review UI`);
